### ISSUE TITLE
Failure on import

### ISSUE THREAD

**Issue by jayjb** [freshbooks/freshbooks-python-sdk#3]
Hi there,

We have migrated across to the new Freshbooks API and thought we would use this sdk. I am experiencing the following issues:

1. When using python 2.7:
```
Traceback (most recent call last):
  File "freshbooks_util.py", line 1, in <module>
    from freshbooks import Client
  File "/Users/me/env/lib/python2.7/site-packages/freshbooks/__init__.py", line 10, in <module>
    from freshbooks.builders.filter import FilterBuilder  # noqa
  File "/Users/me/env/lib/python2.7/site-packages/freshbooks/builders/__init__.py", line 3
    def build(self) -> str:  # pragma: no cover
                    ^
SyntaxError: invalid syntax
```

2. When using python 3.8:
```
Traceback (most recent call last):
  File "freshbooks_util.py", line 1, in <module>
    from freshbooks import Client
  File "/Users/me/38env/lib/python3.8/site-packages/freshbooks/__init__.py", line 13, in <module>
    from freshbooks.client import Client  # noqa
  File "/Users/me/38env/lib/python3.8/site-packages/freshbooks/client.py", line 28, in <module>
    with open(os.path.join(os.path.dirname(__file__), "VERSION")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/me/38env/lib/python3.8/site-packages/freshbooks/VERSION'
```

I realise that the sdk is still < 1.0; but thought I would report these issues to see if there is a quick fix available.

**Comment by amcintosh** [comment]
Hey! Sorry about that. Should be fixed if you grab version 0.3.0 on python 3.6+ (we aren't going to support 2.7).

Thanks for the feedback and bug report!
